import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

import { breakpointScreens } from "./src/lib/breakpoints";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    screens: breakpointScreens,
    extend: {
      colors: {
        canvas: "var(--canvas)",
        "canvas-warm": "var(--canvas-warm)",
        "surface-card": "var(--surface-card)",
        "surface-elev": "var(--surface-elev)",
        background: "var(--canvas)",
        foreground: "var(--ink)",
        card: "var(--canvas)",
        "card-foreground": "var(--ink)",
        primary: "var(--ink)",
        "primary-foreground": "var(--canvas)",
        secondary: "var(--surface-card)",
        "secondary-foreground": "var(--ink)",
        destructive: "var(--error)",
        "destructive-foreground": "var(--canvas)",
        accent: "var(--surface-card)",
        "accent-foreground": "var(--ink)",
        border: "var(--hairline)",
        input: "var(--hairline)",
        ring: "var(--ink)",
        "muted-foreground": "var(--muted)",
        ink: {
          DEFAULT: "var(--ink)",
          soft: "var(--ink-soft)",
        },
        body: "var(--body)",
        muted: "var(--muted)",
        hairline: {
          DEFAULT: "var(--hairline)",
          soft: "var(--hairline-soft)",
        },
        footer: {
          DEFAULT: "var(--footer)",
          soft: "var(--footer-soft)",
        },
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        "success-surface": "var(--status-success-surface)",
        "success-border": "var(--status-success-border)",
        "success-action": "var(--success-action-surface)",
        "success-action-hover": "var(--success-action-surface-hover)",
        "success-action-foreground": "var(--success-action-foreground)",
        "success-action-on-dark": "var(--success-action-foreground-on-dark)",
        "warning-surface": "var(--status-warning-surface)",
        "warning-border": "var(--status-warning-border)",
        "warning-on-dark": "var(--status-warning-foreground-on-dark)",
        "error-surface": "var(--status-error-surface)",
        "error-border": "var(--status-error-border)",
        "success-on-dark": "var(--success-on-dark)",
        "error-on-dark": "var(--error-on-dark)",
        status: {
          success: {
            surface: "var(--status-success-surface)",
            DEFAULT: "var(--status-success-foreground)",
            foreground: "var(--status-success-foreground)",
            border: "var(--status-success-border)",
            "on-dark": "var(--status-success-foreground-on-dark)",
            "border-on-dark": "var(--status-success-border-on-dark)",
          },
          warning: {
            surface: "var(--status-warning-surface)",
            DEFAULT: "var(--status-warning-foreground)",
            foreground: "var(--status-warning-foreground)",
            border: "var(--status-warning-border)",
            "on-dark": "var(--status-warning-foreground-on-dark)",
            "border-on-dark": "var(--status-warning-border-on-dark)",
          },
          error: {
            surface: "var(--status-error-surface)",
            DEFAULT: "var(--status-error-foreground)",
            foreground: "var(--status-error-foreground)",
            border: "var(--status-error-border)",
            "on-dark": "var(--status-error-foreground-on-dark)",
            "border-on-dark": "var(--status-error-border-on-dark)",
          },
        },
        control: {
          surface: "var(--control-surface)",
          "surface-hover": "var(--control-surface-hover)",
          "surface-disabled": "var(--control-surface-disabled)",
          foreground: "var(--control-foreground)",
          "foreground-disabled": "var(--control-foreground-disabled)",
          border: "var(--control-border)",
          "border-hover": "var(--control-border-hover)",
          "border-focus": "var(--control-border-focus)",
          "border-invalid": "var(--control-border-invalid)",
          "border-success": "var(--control-border-success)",
          ring: "var(--control-ring)",
          pressed: "var(--control-pressed-surface)",
        },
        "ink-red": "var(--ink-red)",
        "ink-blue": "var(--ink-blue)",
        overlay: "var(--overlay)",
      },
      borderRadius: {
        pill: "var(--radius-pill)",
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
      },
      spacing: {
        "page-inline": "var(--space-page-inline)",
        "page-inline-lg": "var(--space-page-inline-lg)",
        "page-block": "var(--space-page-block)",
        section: "var(--space-section)",
        "section-lg": "var(--space-section-lg)",
        panel: "var(--space-panel)",
        field: "var(--space-field)",
        "field-compact": "var(--space-field-compact)",
        "control-x": "var(--space-control-x)",
        "control-y": "var(--space-control-y)",
        "control-gap": "var(--space-control-gap)",
        inline: "var(--space-inline)",
        stack: "var(--space-stack)",
        action: "var(--action-gap)",
        "action-group": "var(--action-group-gap)",
        "overlay-padding-top": "var(--overlay-viewport-padding-top)",
        "overlay-padding-bottom": "var(--overlay-viewport-padding-bottom)",
        "overlay-padding-inline": "var(--overlay-viewport-padding-inline)",
      },
      maxWidth: {
        reading: "var(--page-frame-reading)",
        standard: "var(--page-frame-standard)",
        wide: "var(--page-frame-wide)",
        full: "var(--page-frame-full)",
        "page-reading": "var(--page-frame-reading)",
        "page-standard": "var(--page-frame-standard)",
        "page-wide": "var(--page-frame-wide)",
        "page-full": "var(--page-frame-full)",
      },
      minHeight: {
        action: "var(--action-height)",
        "action-compact": "var(--action-height-compact)",
        "action-large": "var(--action-height-large)",
        "touch-target": "var(--exam-focus-touch-target)",
        "exam-focus-target": "var(--exam-focus-touch-target-min)",
      },
      minWidth: {
        action: "var(--action-min-inline)",
        "touch-target": "var(--exam-focus-touch-target)",
        "exam-focus-target": "var(--exam-focus-touch-target-min)",
      },
      height: {
        action: "var(--action-height)",
        "action-compact": "var(--action-height-compact)",
        "action-large": "var(--action-height-large)",
        overlay: "var(--overlay-viewport-height)",
      },
      maxHeight: {
        overlay: "var(--overlay-viewport-max-height)",
      },
      padding: {
        "overlay-top": "var(--overlay-viewport-padding-top)",
        "overlay-bottom": "var(--overlay-viewport-padding-bottom)",
        "overlay-inline": "var(--overlay-viewport-padding-inline)",
      },
      boxShadow: {
        card: "var(--elevation-card)",
        pop: "var(--shadow-pop)",
        elevate: "var(--shadow-elevate)",
        sticky: "var(--shadow-sticky)",
        none: "var(--elevation-none)",
        popover: "var(--elevation-popover)",
        focus: "var(--elevation-focus)",
        overlay: "var(--elevation-overlay)",
        elevation: "var(--elevation-focus)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        shimmer: "shimmer var(--motion-duration-shimmer) var(--motion-ease-linear) infinite",
      },
      fontSize: {
        "display-2xl": [
          "var(--text-display-2xl)",
          {
            lineHeight: "var(--leading-display-2xl)",
            letterSpacing: "var(--tracking-display-tight)",
          },
        ],
        "display-xl": [
          "var(--text-display-xl)",
          {
            lineHeight: "var(--leading-display-xl)",
            letterSpacing: "var(--tracking-display-tight)",
          },
        ],
        "display-lg": [
          "var(--text-display-lg)",
          {
            lineHeight: "var(--leading-display-lg)",
            letterSpacing: "var(--tracking-display-tight)",
          },
        ],
        "display-md": [
          "var(--text-display-md)",
          { lineHeight: "var(--leading-display-md)", letterSpacing: "var(--tracking-display)" },
        ],
        "display-sm": [
          "var(--text-display-sm)",
          { lineHeight: "var(--leading-display-sm)", letterSpacing: "var(--tracking-display)" },
        ],
        "body-lg": ["var(--text-body-lg)", { lineHeight: "var(--leading-body-lg)" }],
        body: ["var(--text-body)", { lineHeight: "var(--leading-body)" }],
        "body-sm": ["var(--text-body-sm)", { lineHeight: "var(--leading-body-sm)" }],
        caption: [
          "var(--text-caption)",
          {
            lineHeight: "var(--leading-caption)",
            letterSpacing: "var(--tracking-caption)",
          },
        ],
        "page-title": [
          "var(--type-page-title-size)",
          {
            lineHeight: "var(--type-page-title-leading)",
            letterSpacing: "var(--type-page-title-tracking)",
          },
        ],
        "section-title": [
          "var(--type-section-title-size)",
          {
            lineHeight: "var(--type-section-title-leading)",
            letterSpacing: "var(--type-section-title-tracking)",
          },
        ],
        "subsection-title": [
          "var(--type-subsection-title-size)",
          {
            lineHeight: "var(--type-subsection-title-leading)",
            letterSpacing: "var(--type-subsection-title-tracking)",
          },
        ],
        nav: [
          "var(--type-nav-size)",
          { lineHeight: "var(--type-nav-leading)", letterSpacing: "var(--type-nav-tracking)" },
        ],
        action: [
          "var(--type-action-size)",
          {
            lineHeight: "var(--type-action-leading)",
            letterSpacing: "var(--type-action-tracking)",
          },
        ],
        status: [
          "var(--type-status-size)",
          {
            lineHeight: "var(--type-status-leading)",
            letterSpacing: "var(--type-status-tracking)",
          },
        ],
        metric: [
          "var(--type-metric-size)",
          {
            lineHeight: "var(--type-metric-leading)",
            letterSpacing: "var(--type-metric-tracking)",
          },
        ],
        question: [
          "var(--type-question-size)",
          {
            lineHeight: "var(--type-question-leading)",
            letterSpacing: "var(--type-question-tracking)",
          },
        ],
        "table-label": [
          "var(--type-table-label-size)",
          {
            lineHeight: "var(--type-table-label-leading)",
            letterSpacing: "var(--type-table-label-tracking)",
          },
        ],
      },
      lineHeight: {
        "page-title": "var(--type-page-title-leading)",
        "section-title": "var(--type-section-title-leading)",
        "subsection-title": "var(--type-subsection-title-leading)",
        nav: "var(--type-nav-leading)",
        action: "var(--type-action-leading)",
        status: "var(--type-status-leading)",
        metric: "var(--type-metric-leading)",
        question: "var(--type-question-leading)",
        "table-label": "var(--type-table-label-leading)",
      },
      letterSpacing: {
        "display-tight": "var(--tracking-display-tight)",
        display: "var(--tracking-display)",
        caption: "var(--tracking-caption)",
        "page-title": "var(--type-page-title-tracking)",
        "section-title": "var(--type-section-title-tracking)",
        "subsection-title": "var(--type-subsection-title-tracking)",
        nav: "var(--type-nav-tracking)",
        action: "var(--type-action-tracking)",
        status: "var(--type-status-tracking)",
        metric: "var(--type-metric-tracking)",
        question: "var(--type-question-tracking)",
        "table-label": "var(--type-table-label-tracking)",
      },
      fontWeight: {
        "page-title": "var(--type-page-title-weight)",
        "section-title": "var(--type-section-title-weight)",
        "subsection-title": "var(--type-subsection-title-weight)",
        nav: "var(--type-nav-weight)",
        action: "var(--type-action-weight)",
        status: "var(--type-status-weight)",
        metric: "var(--type-metric-weight)",
        question: "var(--type-question-weight)",
        "table-label": "var(--type-table-label-weight)",
      },
      transitionDuration: {
        DEFAULT: "var(--motion-duration-fast)",
        instant: "var(--motion-duration-instant)",
        fast: "var(--motion-duration-fast)",
        normal: "var(--motion-duration-normal)",
        slow: "var(--motion-duration-slow)",
        shimmer: "var(--motion-duration-shimmer)",
        pulse: "var(--motion-duration-pulse)",
      },
      transitionTimingFunction: {
        DEFAULT: "var(--motion-ease-standard)",
        linear: "var(--motion-ease-linear)",
        standard: "var(--motion-ease-standard)",
      },
      zIndex: {
        background: "var(--z-background)",
        content: "var(--z-content)",
        sticky: "var(--z-sticky)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
      },
      ringWidth: {
        DEFAULT: "var(--focus-ring-width)",
      },
      ringOffsetWidth: {
        DEFAULT: "var(--focus-ring-offset)",
      },
    },
  },
  plugins: [animate],
} satisfies Config;
