"""add_status_enum_fk_ondelete_and_question_defaults

Revision ID: e2a085da7a47
Revises: 202606110001
Create Date: 2026-06-15 07:14:45.121950
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e2a085da7a47"
down_revision: str | Sequence[str] | None = "202606110001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_candidate_employee_no"), "candidate", type_="unique")
    op.drop_index(op.f("ix_candidate_employee_no"), table_name="candidate")
    op.create_index(
        op.f("ix_candidate_employee_no"), "candidate", ["employee_no"], unique=True
    )
    op.drop_constraint(
        op.f("exam_attempt_exam_id_fkey"), "exam_attempt", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("exam_attempt_candidate_id_fkey"), "exam_attempt", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "exam_attempt", "exam", ["exam_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "exam_attempt", "candidate", ["candidate_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(
        op.f("uq_exam_attempt_answer_attempt_question_id"),
        "exam_attempt_answer",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_exam_attempt_answer_attempt_question_id"),
        table_name="exam_attempt_answer",
    )
    op.create_index(
        op.f("ix_exam_attempt_answer_attempt_question_id"),
        "exam_attempt_answer",
        ["attempt_question_id"],
        unique=True,
    )
    op.alter_column(
        "exam_attempt_question",
        "stem_snapshot",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "exam_attempt_question",
        "analysis_snapshot",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("exam_attempt_question_original_question_id_fkey"),
        "exam_attempt_question",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "exam_attempt_question",
        "question",
        ["original_question_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_question_question_type"), table_name="question")
    op.drop_index(op.f("ix_question_status"), table_name="question")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_question_status"), "question", ["status"], unique=False)
    op.create_index(
        op.f("ix_question_question_type"), "question", ["question_type"], unique=False
    )
    op.drop_constraint(
        op.f("exam_attempt_question_original_question_id_fkey"),
        "exam_attempt_question",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("exam_attempt_question_original_question_id_fkey"),
        "exam_attempt_question",
        "question",
        ["original_question_id"],
        ["id"],
    )
    op.alter_column(
        "exam_attempt_question",
        "analysis_snapshot",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "exam_attempt_question",
        "stem_snapshot",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_exam_attempt_answer_attempt_question_id"),
        table_name="exam_attempt_answer",
    )
    op.create_index(
        op.f("ix_exam_attempt_answer_attempt_question_id"),
        "exam_attempt_answer",
        ["attempt_question_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_exam_attempt_answer_attempt_question_id"),
        "exam_attempt_answer",
        ["attempt_question_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        op.f("exam_attempt_candidate_id_fkey"),
        "exam_attempt",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("exam_attempt_exam_id_fkey"),
        "exam_attempt",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("exam_attempt_candidate_id_fkey"),
        "exam_attempt",
        "candidate",
        ["candidate_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("exam_attempt_exam_id_fkey"), "exam_attempt", "exam", ["exam_id"], ["id"]
    )
    op.drop_index(op.f("ix_candidate_employee_no"), table_name="candidate")
    op.create_index(
        op.f("ix_candidate_employee_no"), "candidate", ["employee_no"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_candidate_employee_no"),
        "candidate",
        ["employee_no"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
