/**
 * TypeScript access to the runtime tokens defined in `src/index.css :root`.
 *
 * The CSS root remains the literal authority. Every value here is deliberately
 * an exact `var(--token-name)` reference so inline styles and dynamic helpers
 * cannot become a second source of visual truth.
 */
export const designTokens = {
  // Surfaces
  canvas: "var(--canvas)",
  canvasWarm: "var(--canvas-warm)",
  surfaceCard: "var(--surface-card)",
  surfaceElev: "var(--surface-elev)",

  // Ink and status
  ink: "var(--ink)",
  inkSoft: "var(--ink-soft)",
  body: "var(--body)",
  muted: "var(--muted)",
  hairline: "var(--hairline)",
  hairlineSoft: "var(--hairline-soft)",
  footer: "var(--footer)",
  footerSoft: "var(--footer-soft)",
  success: "var(--success)",
  warning: "var(--warning)",
  error: "var(--error)",
  inkRed: "var(--ink-red)",
  inkBlue: "var(--ink-blue)",
  successOnDark: "var(--success-on-dark)",
  errorOnDark: "var(--error-on-dark)",
  overlay: "var(--overlay)",

  // Status-on-surface roles. Opaque border values compile deterministically.
  statusSuccessSurface: "var(--status-success-surface)",
  statusSuccessForeground: "var(--status-success-foreground)",
  statusSuccessBorder: "var(--status-success-border)",
  statusSuccessForegroundOnDark: "var(--status-success-foreground-on-dark)",
  statusSuccessBorderOnDark: "var(--status-success-border-on-dark)",
  statusWarningSurface: "var(--status-warning-surface)",
  statusWarningForeground: "var(--status-warning-foreground)",
  statusWarningBorder: "var(--status-warning-border)",
  statusWarningForegroundOnDark: "var(--status-warning-foreground-on-dark)",
  statusWarningBorderOnDark: "var(--status-warning-border-on-dark)",
  statusErrorSurface: "var(--status-error-surface)",
  statusErrorForeground: "var(--status-error-foreground)",
  statusErrorBorder: "var(--status-error-border)",
  statusErrorForegroundOnDark: "var(--status-error-foreground-on-dark)",
  statusErrorBorderOnDark: "var(--status-error-border-on-dark)",
  successActionSurface: "var(--success-action-surface)",
  successActionSurfaceHover: "var(--success-action-surface-hover)",
  successActionForeground: "var(--success-action-foreground)",
  successActionForegroundOnDark: "var(--success-action-foreground-on-dark)",

  // Radius and elevation
  radiusPill: "var(--radius-pill)",
  radiusLg: "var(--radius-lg)",
  radiusMd: "var(--radius-md)",
  radiusSm: "var(--radius-sm)",
  shadowCard: "var(--shadow-card)",
  shadowPop: "var(--shadow-pop)",
  shadowElevate: "var(--shadow-elevate)",
  shadowSticky: "var(--shadow-sticky)",
  elevationNone: "var(--elevation-none)",
  elevationCard: "var(--elevation-card)",
  elevationPopover: "var(--elevation-popover)",
  elevationFocus: "var(--elevation-focus)",
  elevationOverlay: "var(--elevation-overlay)",
  elevationSticky: "var(--elevation-sticky)",

  // Fonts
  fontDisplay: "var(--font-display)",
  fontBody: "var(--font-body)",
  fontMono: "var(--font-mono)",

  // Type scale, line heights, and tracking
  textDisplay2xl: "var(--text-display-2xl)",
  textDisplayXl: "var(--text-display-xl)",
  textDisplayLg: "var(--text-display-lg)",
  textDisplayMd: "var(--text-display-md)",
  textDisplaySm: "var(--text-display-sm)",
  textBodyLg: "var(--text-body-lg)",
  textBody: "var(--text-body)",
  textBodySm: "var(--text-body-sm)",
  textCaption: "var(--text-caption)",
  leadingDisplay2xl: "var(--leading-display-2xl)",
  leadingDisplayXl: "var(--leading-display-xl)",
  leadingDisplayLg: "var(--leading-display-lg)",
  leadingDisplayMd: "var(--leading-display-md)",
  leadingDisplaySm: "var(--leading-display-sm)",
  leadingBodyLg: "var(--leading-body-lg)",
  leadingBody: "var(--leading-body)",
  leadingBodySm: "var(--leading-body-sm)",
  leadingCaption: "var(--leading-caption)",
  trackingDisplayTight: "var(--tracking-display-tight)",
  trackingDisplay: "var(--tracking-display)",
  trackingCaption: "var(--tracking-caption)",

  // Semantic editorial type roles.
  typePageTitleSize: "var(--type-page-title-size)",
  typePageTitleLeading: "var(--type-page-title-leading)",
  typePageTitleWeight: "var(--type-page-title-weight)",
  typePageTitleTracking: "var(--type-page-title-tracking)",
  typeSectionTitleSize: "var(--type-section-title-size)",
  typeSectionTitleLeading: "var(--type-section-title-leading)",
  typeSectionTitleWeight: "var(--type-section-title-weight)",
  typeSectionTitleTracking: "var(--type-section-title-tracking)",
  typeSubsectionTitleSize: "var(--type-subsection-title-size)",
  typeSubsectionTitleLeading: "var(--type-subsection-title-leading)",
  typeSubsectionTitleWeight: "var(--type-subsection-title-weight)",
  typeSubsectionTitleTracking: "var(--type-subsection-title-tracking)",
  typeNavSize: "var(--type-nav-size)",
  typeNavLeading: "var(--type-nav-leading)",
  typeNavWeight: "var(--type-nav-weight)",
  typeNavTracking: "var(--type-nav-tracking)",
  typeActionSize: "var(--type-action-size)",
  typeActionLeading: "var(--type-action-leading)",
  typeActionWeight: "var(--type-action-weight)",
  typeActionTracking: "var(--type-action-tracking)",
  typeStatusSize: "var(--type-status-size)",
  typeStatusLeading: "var(--type-status-leading)",
  typeStatusWeight: "var(--type-status-weight)",
  typeStatusTracking: "var(--type-status-tracking)",
  typeMetricSize: "var(--type-metric-size)",
  typeMetricLeading: "var(--type-metric-leading)",
  typeMetricWeight: "var(--type-metric-weight)",
  typeMetricTracking: "var(--type-metric-tracking)",
  typeQuestionSize: "var(--type-question-size)",
  typeQuestionLeading: "var(--type-question-leading)",
  typeQuestionWeight: "var(--type-question-weight)",
  typeQuestionTracking: "var(--type-question-tracking)",
  typeTableLabelSize: "var(--type-table-label-size)",
  typeTableLabelLeading: "var(--type-table-label-leading)",
  typeTableLabelWeight: "var(--type-table-label-weight)",
  typeTableLabelTracking: "var(--type-table-label-tracking)",

  // Semantic layout spacing
  spacePageInline: "var(--space-page-inline)",
  spacePageInlineLg: "var(--space-page-inline-lg)",
  spacePageBlock: "var(--space-page-block)",
  spaceSection: "var(--space-section)",
  spaceSectionLg: "var(--space-section-lg)",
  spacePanel: "var(--space-panel)",
  spaceField: "var(--space-field)",
  spaceFieldCompact: "var(--space-field-compact)",
  spaceControlX: "var(--space-control-x)",
  spaceControlY: "var(--space-control-y)",
  spaceControlGap: "var(--space-control-gap)",
  spaceInline: "var(--space-inline)",
  spaceStack: "var(--space-stack)",

  // Page-frame and action roles.
  pageFrameReading: "var(--page-frame-reading)",
  pageFrameStandard: "var(--page-frame-standard)",
  pageFrameWide: "var(--page-frame-wide)",
  pageFrameFull: "var(--page-frame-full)",
  pageFrameInline: "var(--page-frame-inline)",
  pageFrameInlineLg: "var(--page-frame-inline-lg)",
  pageFrameBlock: "var(--page-frame-block)",
  pageFrameSectionGap: "var(--page-frame-section-gap)",
  actionHeightCompact: "var(--action-height-compact)",
  actionHeight: "var(--action-height)",
  actionHeightLarge: "var(--action-height-large)",
  actionMinInline: "var(--action-min-inline)",
  actionPaddingInline: "var(--action-padding-inline)",
  actionGap: "var(--action-gap)",
  actionGroupGap: "var(--action-group-gap)",
  examFocusTouchTarget: "var(--exam-focus-touch-target)",
  examFocusTouchTargetMin: "var(--exam-focus-touch-target-min)",

  // Control state roles.
  controlSurface: "var(--control-surface)",
  controlSurfaceHover: "var(--control-surface-hover)",
  controlSurfaceDisabled: "var(--control-surface-disabled)",
  controlForeground: "var(--control-foreground)",
  controlForegroundDisabled: "var(--control-foreground-disabled)",
  controlBorder: "var(--control-border)",
  controlBorderHover: "var(--control-border-hover)",
  controlBorderFocus: "var(--control-border-focus)",
  controlBorderInvalid: "var(--control-border-invalid)",
  controlBorderSuccess: "var(--control-border-success)",
  controlRing: "var(--control-ring)",
  controlPressedSurface: "var(--control-pressed-surface)",

  // Dynamic overlay viewport and safe-area roles.
  overlayViewportHeight: "var(--overlay-viewport-height)",
  overlayViewportMaxHeight: "var(--overlay-viewport-max-height)",
  overlayViewportPaddingTop: "var(--overlay-viewport-padding-top)",
  overlayViewportPaddingBottom: "var(--overlay-viewport-padding-bottom)",
  overlayViewportPaddingInline: "var(--overlay-viewport-padding-inline)",

  // Focus-visible treatment
  focusRingWidth: "var(--focus-ring-width)",
  focusRingColor: "var(--focus-ring-color)",
  focusRingOffset: "var(--focus-ring-offset)",
  focusRingRadius: "var(--focus-ring-radius)",

  // Motion
  motionDurationInstant: "var(--motion-duration-instant)",
  motionDurationFast: "var(--motion-duration-fast)",
  motionDurationNormal: "var(--motion-duration-normal)",
  motionDurationSlow: "var(--motion-duration-slow)",
  motionDurationShimmer: "var(--motion-duration-shimmer)",
  motionDurationPulse: "var(--motion-duration-pulse)",
  motionEaseLinear: "var(--motion-ease-linear)",
  motionEaseStandard: "var(--motion-ease-standard)",
  motionDistanceRise: "var(--motion-distance-rise)",
  motionStaggerStep: "var(--motion-stagger-step)",
  motionStaggerMax: "var(--motion-stagger-max)",

  // Layering
  zBackground: "var(--z-background)",
  zContent: "var(--z-content)",
  zSticky: "var(--z-sticky)",
  zOverlay: "var(--z-overlay)",
  zModal: "var(--z-modal)",
  zToast: "var(--z-toast)",

  // Named admin-login texture
  textureAdminLoginDot: "var(--texture-admin-login-dot)",
  textureAdminLoginDotSize: "var(--texture-admin-login-dot-size)",
  textureAdminLoginSize: "var(--texture-admin-login-size)",
} as const;

export type DesignTokenKey = keyof typeof designTokens;
export type DesignTokenValue = (typeof designTokens)[DesignTokenKey];
